name: On Tag with Branch Condition

on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  publish:
    name: On Tag with Branch Condition
    runs-on: ubuntu-latest
    steps:
      - name: Set Branch Var 
        run: echo "BRANCH=$(echo git branch --contains ${{ github.ref }}" >> $GITHUB_ENV
      - name: Test Branch Var
        run: echo $BRANCH
      - name: Branch Condition
        if: $BRANCH == 'refs/heads/main'
        run: echo "True!" 
